export default [
  //exportAll:1)true全部数据;2)false,不导出;3)thisPart,本页面
  { name: 'index_contant', exportAll: false },
  { name: 'lz', exportAll: true },
  { name: 'zx', exportAll: true },
  { name: 'user', exportAll: false },
  { name: 'role', exportAll: false },
  { name: 'user_role', exportAll: false },
  { name: 'post', exportAll: true },
  { name: 'dept', exportAll: false },
  { name: 'kind', exportAll: true },
  { name: 'set', exportAll: false },
  { name: 'work', exportAll: true },
  { name: 'thb', exportAll: true },
  { name: 'staff', exportAll: true },
  { name: 'bg', exportAll: false },
  { name: 'gongxin', exportAll: true },
  { name: 'pdt', exportAll: false },
  { name: 'gtx', exportAll: false },
  { name: 'update_pw', exportAll: false },
  { name: 'rk', exportAll: false },
  { name: 'ck', exportAll: false },
  { name: 'material', exportAll: true },
  { name: 'zf', exportAll: true },
  { name: 'gxcx', exportAll: false },
  { name: 'cl', exportAll: true },
];
